var provinceData = [
    { province: "新疆维吾尔自治区", className: "Z-SF1" },
    { province: "西藏", className: "Z-SF2" },
    { province: "甘肃省", className: "Z-SF3" },
    { province: "青海", className: "Z-SF4" },
    { province: "内蒙古", className: "Z-SF5" },
    { province: "宁夏", className: "Z-SF6" },
    { province: "四川省", className: "Z-SF7" },
    { province: "云南省", className: "Z-SF8" },
    { province: "山西省", className: "Z-SF9" },
    { province: "陕西省", className: "Z-SF10" },
    { province: "湖北省", className: "Z-SF11" },
    { province: "重庆市", className: "Z-SF12" },
    { province: "贵州省", className: "Z-SF13" },
    { province: "广西省", className: "Z-SF14" },
    { province: "北京市", className: "Z-SF15" },
    { province: "河北省", className: "Z-SF16" },
    { province: "河南省", className: "Z-SF17" },
    { province: "湖南省", className: "Z-SF18" },
    { province: "广东省", className: "Z-SF19" },
    { province: "天津市", className: "Z-SF20" },
    { province: "山东省", className: "Z-SF21" },
    { province: "江苏省", className: "Z-SF22" },
    { province: "安徽省", className: "Z-SF23" },

    { province: "上海市", className: "Z-SF24" },
    { province: "浙江省", className: "Z-SF25" },
    { province: "江西省", className: "Z-SF26" },
    { province: "福建省", className: "Z-SF27" },
    { province: "黑龙江省", className: "Z-SF28" },
    { province: "吉林省", className: "Z-SF29" },
    { province: "辽宁省", className: "Z-SF30" },
    { province: "台湾", className: "Z-SF31" },
    { province: "香港", className: "Z-SF32" },
    { province: "澳门", className: "Z-SF33" },
    { province: "海南省", className: "Z-SF34" }
]

let dd = [
    { areaName: '重庆', count: 6 },
    { areaName: '渝西', count: 4 },
    { areaName: '渝东', count: 1 },
    { areaName: '西部', count: 2 },
    { areaName: '贵州', count: 0 },
    { areaName: '云南', count: 0 },
    { areaName: '中原', count: 2 },
    { areaName: '山东', count: 1 },
    { areaName: '华东', count: 1 },
    { areaName: '华北', count: 2 },
    { areaName: '华中', count: 1 },
    { areaName: '华南', count: 0 },
    { areaName: '新疆', count: 0 },
];